version: '2'

services:
    load_balancer:
        image: bitnami/nginx
        ports:
            - 80:8080
            - 443:8443
        depends_on:
            - laravel
            - wordpress
            - phpmyadmin

        volumes:
            - ./dockers/load_balancer/logs:/opt/bitnami/nginx/logs
            - ./dockers/load_balancer/nginx:/bitnami/nginx

    laravel:
        image: bitnami/nginx

        depends_on:
            - phpfpm_laravel
        volumes:
            - ./dockers/laravel/logs:/opt/bitnami/nginx/logs
            - ./dockers/laravel/nginx:/bitnami/nginx
            - ./laravel:/app:consistent

    phpfpm_laravel:
        image: bitnami/php-fpm
        volumes:
            - ./dockers/laravel/phpfpm:/bitnami/php-fpm
            - ./laravel:/app:consistent

    wordpress:
        image: bitnami/nginx

        depends_on:
            - phpfpm_wordpress
        volumes:
            - ./dockers/wordpress/logs:/opt/bitnami/nginx/logs
            - ./dockers/wordpress/nginx:/bitnami/nginx
            - ./wordpress:/app:consistent

    phpfpm_wordpress:
        image: bitnami/php-fpm
        volumes:
            - ./dockers/wordpress/phpfpm:/bitnami/php-fpm
            - ./wordpress:/app:consistent


    mysql:
        image: bitnami/mysql
        volumes:
            - ./dockers/mysql/db/data:/bitnami/mysql
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_USER=my_user
            - MYSQL_PASSWORD=my_password
            - MYSQL_DATABASE=my_database

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        depends_on:
            - mysql
        environment:
            MYSQL_USERNAME: root
            PMA_HOST: mysql